config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :profiles
    resources :dogs
    resources :listings do
      resources :photos
    end
  end
  resources :listings
  root 'statics#index'
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  has_attached_file :dog_avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/thumb/missing.png"
  validates_attachment_content_type :dog_avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  validates :address, :zipcode, :title, :describtion, :property_type, :dog_type, presence: true
  geocoded_by :address    
  after_validation :geocode          # auto-fetch coordinates
  
  def self.search(search)
  where("zipcode LIKE ?", "%#{search}%")    
  end

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  has_many :dogs
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :listing
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/thumb/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  has_one :listing, dependent: :destroy
  has_many :dogs, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # after_create :create_profile
  #
  # def create_profile
  #   Profile.create(user: self)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :configure_permitted_parameters, if: :devise_controller?
  #
  # protected
  #
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) do |u|
  #     u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
  #   end
  # end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @dogs = @user.dogs

  end

  def new
    @user = User.find(params[:user_id])
    @dog = @user.dogs.new
  end

  def edit
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @dog = @user.dogs.new(dog_params)
    if @dog.save
      respond_to do |format|
        format.html {redirect_to user_dogs_path(@user, @dog)}
        format.js
      end
    else
      render :index
    end
  end

  def update
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])
    @dog.update(dog_params)
    respond_to do |format|
      format.html {redirect_to user_dogs_path(@user, @dog)}
      format.js
    end

  end

  def destroy
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])
    @dog.destroy
    redirect_to  user_dogs_path(@user)

  end


  private
    def dog_params
      params.require(:dog).permit(:name, :age, :gender, :breed, :size, :discribtion, :user_id, :dog_avatar)
    end

    def find_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index  
    @listings = Listing.all
    if params[:search]
      @listings = Listing.search(params[:search]) 
    else
      @listings = Listing.all 
    end
  end
  
  def show 
    @listing = Listing.find(params[:id])
     
  end

  def new
    @user = User.find(params[:user_id])
    @listing = Listing.new
    @listing.dog_type = []
    @profile = @user.profile
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @listing = @user.listing
    @dog_type = params[:dog_type] || []
    @photos = @listing.photos
  end

  def create
    @user = User.find(params[:user_id])
    @listing = Listing.new(listing_params)
    @user.listing = @listing
    if @listing.save
      if params[:images].present?
        params[:images].each do |image|
          @listing.photos.create(:image => image)
        end
      end
      redirect_to edit_user_listing_path(@user,@listing)
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:user_id])
    @listing = Listing.find(params[:id])
    @dog_type = params[:dog_type] || []
    if @listing.update(listing_params)
      if params[:images].present?
        params[:images].each do |image|
          @listing.photos.create(:image => image)
        end
      end
      respond_to do |format|
        format.html {redirect_to edit_user_listing_path(@user, @listing)}
        format.js
      end
    end
  end

  private
    def listing_params
      params.require(:listing).permit(:address, :zipcode, :title, :describtion, :property_type, dog_type:[])
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @user = User.find(params[:user_id])
    @user.listing.photos.find(params[:id]).destroy
    redirect_to edit_user_listing_path(@user, @user.listing)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def new
    @user = User.find(params[:user_id])
    @profile = Profile.new

  end

  def create
    @user = User.find(params[:user_id])
    @profile = Profile.new(profile_params)
    if @profile.save
      @user.profile = @profile
      redirect_to edit_user_profile_path(current_user,current_user.profile)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @profile = Profile.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @dogs = @user.dogs

  end

  def update
    @user = User.find(params[:user_id])
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    respond_to do |format|
      format.html {redirect_to edit_user_profile_path(@user, @profile)}
      format.js
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :mobile_number, :avatar)

    end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index

  end

  def profile
    @user = current_user
    @owner = Owner.new()
    render :profile

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/dogs/_dogform.html.erb
<%= form_for [@user, @dog], remote:true do |f| %>
  <p>
    <%= f.text_field :name, placeholder: "Dog's Name" %>
  </p>
  <p>
    <%= f.text_field :age, placeholder: "Age" %>
  </p>
  <p>
    <%= f.text_field :gender, placeholder: "Gender" %>
  </p>
  <p>
    <%= f.text_field :breed, placeholder: "Breed" %>
  </p>
  <p>
    <%= f.text_field :size, placeholder: "Size" %>
  </p>
  <p>
    <%= f.text_area :describtion, placehold: 'Discribe Your Dog' %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/dogs/_dogs.html.erb
 <strong>Dog's name: </string><%= @dog.name%><br>
  <%= link_to 'Edit', edit_user_dog_path(@user, @dog), class: 'btn btn-primary', remote: true%>
  <%= link_to 'Reomove This Dog', user_dog_path(@user, @dog), class: 'btn btn-primary', method: :delete, data:
  {confirm: 'Are your sure?'} %>

app/views/dogs/_form.html.erb
<%= form_for [@user, @dog], remote:true do |f| %>
  <div class="form-group">
    <label for="name">Dog's name:</label>
    <%= f.text_field :name, placeholder: "Dog's Name", class: 'form-control'%>
  </div>
  <div class="form-group">
    <label for="age">Age:</label>
    <%= f.text_field :age, placeholder: "Age", class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="gender">Gender:</label>
    <%= f.select :gender, ['Female', 'Male'], class: 'form-control'%>
  </div>

  <div class="form-group">
    <label for="breed">Breed:</label>
    <%= f.text_field :breed, placeholder: "Breed", class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="size">Size:</label>
    <%= f.select :size, ["Toy(<10 pounds)", "Small(10-20 pounds)", "Meduim(20-40 pounds)", "Large(40-80 pounds)", "Extra Large(80+ pounds)"] %>
  </div>

  <div class="form-group">
    <label for="describtion">Describe your dog: </label>
    <%= f.text_area :describtion, placehold: 'Discribe Your Dog', class: 'form-control' %>
  </div>

  <div class="radio">
    <p>
      Is your dog sprayed or neunered?
    </p>
    <label>
      <%= f.radio_button :fixed, 'yes' %>Yes
    </label>
  </div>

  <div class="radio">
    <label> <%= f.radio_button :fixed, 'no' %>No </label>
  </div>

  <div class="radio">
    <label><%= f.radio_button :fixed, 'not sure' %>Not sure</label>
  </div>


  <div class="radio">
    <p>
      Is your dog friendly with the other dogs?
    </p>
    <label><%= f.radio_button :friendly, 'yes' %>Yes</label>
  </div>
  <div class="radio">
    <label><%= f.radio_button :friendly, 'no' %>No</label>
  </div>
  <div class="radio">
    <label><%= f.radio_button :friendly, 'not sure' %>Not sure</label>
  </div>

  <div class="form-group">
    <label>Upload a photo of your dog:</label>
    <%= f.file_field :dog_avatar, :class => 'form-control'%>

  </div>

    <%= f.submit 'Save&continue', class: 'btn btn-primary'%>
<% end %>

app/views/dogs/create.js.erb
$('#dog_list').append("<li><%= j render 'dogs' %></li>");
$('#new-dog-form').empty();

app/views/dogs/edit.js.erb
$('#new-dog-form').html("<%= j (render 'form') %>");

app/views/dogs/index.html.erb
<div class='row'>
  <h3>Click a section below to edit</h3>
  <div class='col-md-3'>
    <% if current_user.profile.present?%>
      <%= link_to 'About you', edit_user_profile_path(@user, @profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>
    <% else %>
      <%= link_to 'About you', new_user_profile_path(@user,@profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>

    <% end %>
  </div>
  <div class='col-md-9' id='profile_form'>
    <h4>About Your Dogs</h4>
    <p>
      <%= link_to 'Add Another dog', new_user_dog_path, remote: true, class: 'btn btn-primary'%>
    </p>

    <div style='border: solid'>
      <ul id='dog_list' style='list-style: none;'>
        <% if @user.dogs.any? %>
          <% @user.dogs.each do |dog|%>
            <li id="dog-<%= dog.id %>">
              <% if dog.dog_avatar.present? %>
                <%= image_tag(dog.dog_avatar.url(:medium), :class => "dog-image-200")%>
              <% end %>
              <strong>Dog name: </string><%= dog.name%><br>
              <strong>Breed: </string><%= dog.breed%><br>
              <%= link_to 'Edit', edit_user_dog_path(@user, dog), class: 'btn btn-primary', remote: true%>
              <%= link_to 'Reomove This Dog', user_dog_path(@user, dog), class: 'btn btn-primary', method: :delete, data:
              {confirm: 'Are your sure?'} %>
            </li>
          <% end %>
        <% else %>
          <div class="">
            <p>
              Your currently have no dogs, please add your first dog below.
            </p>

          </div>


        <% end %>

      </ul>
    </div>
    <div class="row">
      <div id='new-dog-form' class='col-md-4'>

      </div>
    </div>

  </div>
</div>

app/views/dogs/new.html.erb
<h2>About Your Dogs</h2>
<h2>Add Dog</h2>
<%= render 'form'%>

app/views/dogs/new.js.erb
$('#new-dog-form').html("<%= j render 'form' %>");
// $('#new-dog-form').show();

app/views/dogs/update.js.erb
$('#dog-<%= @dog.id %>').html("<%= j render 'dogs' %>");
$('#new-dog-form').empty();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pawesome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar-default'>
    <div class='container-fluid'>
      <div class="row">
        <div class="col-md-9 col-md-offset-1">
          <div class='navbar-header'>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="/" class='navbar-brand' style="font-size: 2em">Pawesome</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
              <li>
                <%= link_to listings_path do%>
                  Find a sitter
                <% end %> 
              </li>
               
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if current_user.profile.present? %>
                      <%= image_tag(current_user.profile.avatar.url(:thumb), :class => "round-image-50")%>
                      <%= current_user.profile.first_name %>
                    <% else%>
                      <img src="/images/thumb/missing.png" class='round-image-50' alt="" />
                      hi
                    <% end %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <% if current_user.profile.present? %>
                      <li><%= link_to 'Profile', edit_user_profile_path(current_user,current_user.profile) %></li>
                    <% else %>
                      <li><%= link_to 'Profile', new_user_profile_path(current_user) %></li>
                    <% end %>

                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <% if current_user.listing.present?%>
                      <li><%= link_to 'Your listing', edit_user_listing_path(current_user, current_user.listing)%></li>

                    <% else%>
                      <li><%= link_to 'Become a sitter', new_user_listing_path(current_user)%></li>
                    <% end %>
                    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>


              <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
            </ul>

          </div>
        </div>      
      </div>      
    </div>
  </nav>
  <main>
    <div class='container-fluid' style="margin: 0; padding: 0">  
      <%= yield %>                  
    </div>
  </main>


</body>
</html>

app/views/listings/_form.html.erb
<%= form_for [@user, @listing], html: {multipart: true} do |f| %>

  <div class="form-group">
    <label for="address" >Your full address:</label>
    <%= f.text_field :address, placeholder: "Address", :class => 'form-control' %>
  </div>
  
  <div class="form-group">
    <label for="zipcode" >Zipcode:</label>
    <%= f.text_field :zipcode, placeholder: "Zipcode", :class => 'form-control' %>
  </div>
  
  <div class="form-group">
    <label for="title">You title ex:Butter and friends</label>
    <%= f.text_field :title, placeholder: "Title(20 characters or less)", :class => 'form-control' %>
  </div>
  <div class="form-group">
    <label for="describtion">Describe your self, what make your a great host for your furry friends</label>
    <%= f.text_area :describtion, :class => 'form-control'%>
  </div>

  <div class="form-group">
    <label for="property_type">Property type:</label>
    <%= f.select :property_type, ["Apartment", "House", "Ranch"] %>
  </div>

  <div class='check-box'>
    <label for='dog_type'>
      Which dog size(s) will you host?* (Check all that apply.)
    </label>
    <p><%= check_box_tag('listing[dog_type][]', 'Small (0-20lbs)', @listing.dog_type.include?('Small (0-20lbs)')) %> Small (0-20lbs)</p>
    <p><%= check_box_tag('listing[dog_type][]', 'Medium (20-40lbs)', @listing.dog_type.include?('Medium (20-40lbs)')) %> Medium (20-40lbs)</p>
    <p><%= check_box_tag('listing[dog_type][]', 'Large (40-80lbs)', @listing.dog_type.include?('Large (40-80lbs)')) %> Large (40-80lbs)</p>
    <p><%= check_box_tag('listing[dog_type][]', 'Giant (80+lbs)', @listing.dog_type.include?('Giant (80+lbs)')) %> Giant (80+lbs)</p>
  </div>

  <div class="form-group">
    <label for="listing_photo">Upload photos for your business:</label>
    <%= file_field_tag "images[]", type: :file, multiple: true %>

  </div>
  <%= f.submit "Save&continue", class: 'btn btn-primary'%>

<% end %>

app/views/listings/edit.html.erb
<div class='row'>
  <h3>Click a section below to edit</h3>
  <div class='col-md-3'>
    <% if current_user.profile.present?%>
      <%= link_to 'About you', edit_user_profile_path(@user, @profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>
    <% else %>
      <%= link_to 'About you', new_user_profile_path(@user,@profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>

    <% end %>
  </div>
  <div class='col-md-9'>
    <div class="row">
      <div class='col-md-8'>
        <%= render 'form' %>
      </div>
      <div class='col-md-4'>
        <h3>Your Photos: </h3>
        <div style='border: dashed; text-align: center;'>
          <strong>
            To Delete Images:
          </strong>
          <p>
            Hover over an image and click "X"
          </p>

        </div>

        <div >
          <ul style='list-style: none; display: inline-block'>
            <% @photos.each do |photo| %>
                <li id="photo-<%= photo.id %>" style='display: inline-block'>
                  <div style='position: relative; display: inline-block'  class='photos'>
                    <%= image_tag photo.image.url(:thumb) %>
                    <div style='position: absolute; top: 0; right: 0; background-color: #29293d; border-radius: 50%; width:1.5em; height: 1.5em; text-align: center;' class='delete-photo' id="delete-photo-<%= photo.id %>">
                      <%= link_to 'X', user_listing_photo_path(@user, @listing, photo), method: :delete%>
                    </div>
                  </div>
                </li>
            <% end %>

          </ul>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
   
      <div class="row">
        <% @listings.each do |listing| %>
          <%= link_to listing_path(listing.id) do%>
            <div class="col-md-7 listings" style="height: 15em; margin-bottom: 0.5em; background-color: #ffffff; box-sizing: border-box;">
              <div class="row">
                <div class="col-sm-2" style='background-color: rgb(216,	221, 222); padding: 2px; height: 14.85em; margin-bottom: 0.5em;'>     
                  <% if listing.user.profile.avatar.present?%>
                    <%= image_tag(current_user.profile.avatar.url(:medium), :class => "profile-image-200")%>
                  <% else %>
                    <img src="/images/thumb/missing.png" class='profile-image-200' alt="" style="width: 99%; height: 50%" />
                  <% end %>                      
                </div>
                <div class="col-sm-10">
                  <h3><%= listing.title %></h3>
                  <p>
                    <strong><%= listing.user.profile.first_name %><span> </span></strong><%= listing.address %>
                  </p> 
                  <p>
                    <%= listing.describtion %>
                  </p>
                </div>
                
              </div>
                     
            </div>
          <% end %>
        <% end %>
        <div class="col-md-5">
          <!-- <img src="https://maps.googleapis.com/maps/api/staticmap?center=portland, oregon&size=500x600&key=AIzaSyCHJqE8WTFV0eu2F2bR32EzFBrL465BI6s"> -->
          <% my_url = "https://maps.googleapis.com/maps/api/staticmap?&size=500x600&key=AIzaSyCHJqE8WTFV0eu2F2bR32EzFBrL465BI6s" %>
          <% @listings.each do |listing| %> 
          <% my_url += "&markers=color:red|#{listing.latitude}%2C#{listing.longitude}" %>    
          <% end %>
          <%= image_tag my_url %>
          
        </div>
      </div>
  </div>
  
</div>

app/views/listings/new.html.erb
<div class='row'>
  <h3>Click a section below to edit</h3>
  <div class='col-md-3'>
    <% if current_user.profile.present?%>
      <%= link_to 'About you', edit_user_profile_path(@user, @profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>
    <% else %>
      <%= link_to 'About you', new_user_profile_path(@user,@profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>

    <% end %>
  </div>
  <div class='col-md-9'>
    <div class="row">
      <div id='new-listing-form' class='col-md-4'>
        <%= render 'form'%>

      </div>
    </div>

  </div>
</div>

app/views/listings/show.html.erb
 <div class="row">
   <div class="col-md-10 col-md-offset-1">
     <div class="col-md-9">
       <h3><%= @listing.title %></h3>
       <div class="">
         <h4>About <%= @listing.user.profile.first_name %></h4>
         <p>
           <%= @listing.describtion %>
         </p>
       </div>
       
       <div class="">
         <h4>Details</h4>
         
       </div>
       
       
     </div>
   </div>
  
  
  
</div>

app/views/profiles/_form.html.erb
<%= form_for [@user, @profile] do |f| %>

  <div class="form-group">
    <label for="first_name">First name:</label>
    <%= f.text_field :first_name, placeholder: "First name", :class => 'form-control' %>
  </div>
  <div class="form-group">
    <label for="last_name">Last name:</label>
    <%= f.text_field :last_name, placeholder: "Last name", :class => 'form-control' %>
  </div>
  <div class="form-group">
    <label for="mobile_number">Mobile number:</label>
    <%= f.text_field :mobile_number, placeholder: "mobile_number", :class => 'form-control'%>
  </div>

  <div class="form-group">
    <label for="avatar">Upload a photo of yourself:</label>
    <%= f.file_field :avatar, :class => 'form-control'%>

  </div>
  <%= f.submit "Save&continue", class: 'btn btn-primary'%>



<% end %>

app/views/profiles/edit.html.erb
<div class='row'>
  <h3>Click a section below to edit</h3>
  <div class='col-md-3'>
      <%= link_to 'About you', edit_user_profile_path(@user,@profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>
  </div>
  <div class='col-md-9' id='profile_form'>
    <div class="row">
      <div class="col-md-4">
        <%= render 'form' %>
      </div>

      <div class="col-md-4" class='profile-image-div'>
        <% if current_user.profile.avatar.present?%>
          <%= image_tag(current_user.profile.avatar.url(:medium), :class => "profile-image-200")%>
        <% else %>
          <img src="/images/thumb/missing.png" class='profile-image-200' alt="" />
        <% end %>
        <p>
          Your photo
        </p>

      </div>



    </div>


  </div>
</div>

app/views/profiles/new.html.erb
<div class='row'>
  <h3>Click a section below to edit</h3>
  <div class='col-md-3'>
      <%= link_to 'About you', new_user_profile_path(@user,@profile), class: 'btn btn-primary'%><br>
      <%= link_to 'Your dog', user_dogs_path(@user, @dogs), class: 'btn btn-primary'%>
  </div>
  <div class='col-md-9' id='profile_form'>
    <div class="row">
      <div class="col-md-4">
        <%= render 'form' %>
      </div>
      <div class="col-md-4">
        <% if current_user.profile.avatar.present?%>
          <%= image_tag(current_user.profile.avatar.url(:medium), :class => "profile-image-200")%>
        <% else %>
          <img src="/images/thumb/missing.png" class='profile-image-200' alt="" />
        <% end %>

      </div>

    </div>





  </div>
</div>

app/views/statics/index.html.erb
<div class="jumbotron">
</div>
<div class="row">
  <h1 style="text-align: center">
    Find a <em style='color: red'>Pawesome</em> pet sitter near you
  </h1>  
</div>
<div class="row">
  <div class="form-inline" style="text-align: center">
    <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    <%= text_field_tag :search, params[:search], placeholder: "Zipcode or Address", :class => "form-control"%>
    <%= submit_tag "FIND A SITTER", :class => "form-control" %>
    <% end %>
  </div>
</div>
 

app/views/statics/profile.html.erb
<div class='row'>
  <div class='col-md-3'>
    <h3>Click a section below to edit</h3>
    <%= link_to 'About you', new_user_owner_path(@user), remote: true, class: 'btn btn-primary'%><br>
    <%= link_to 'Your dog', class: 'btn btn-primary'%>
  </div>

  <div class='col-md-9'>
    <div id='form'>

    </div>
  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>